### PR TITLE
Mechanism 1

### PR DESCRIPTION
**Pull request by tinhangchui**
Briefly finished the mechanism, see check_adjacement() function. The
function works but I think it can be better.
I also changed the event system. Now it "waits" for event, which reduced
the CPU usage (from 25% to 0%)!
Deleted some unnecessary files.

### CODE REVIEW

**Comment by tinhangchui** [comment]
I give up...Maybe fork it again is easier....

**Comment by banhathome** [comment]
Hey, what happened?

**Comment by tinhangchui** [comment]
I tried to update the repository, but Github can't merge the commits.

**Comment by banhathome** [comment]
@sith0726, I'll get back to you in a bit on how to fix this. Do you have a Skype or something so that we can discuss this easier. My Skype is chrisngobanh

**Comment by tinhangchui** [comment]
I solved the problem by simply creating a new branch and merge it with the master. Now it's up-to-date now.

**Pull request closed without merging**
